### ISSUE TITLE
TuneOut No work!!!! :(

### ISSUE THREAD

**Issue by Ula492** [wonaldson/tuneout#13]
My OBS wont find the file on Application support?

**Comment by wonaldson** [comment]
The track data file is located at `~/Library/Application Support/TuneOut/np.txt`, where `~` consists of your User folder (usually `/Users/{your user name here}`). So if your computer account was called Ula492, the file would be located at `/Users/Ula492/Library/Application Support/TuneOut/np.txt`. Ensure you've started TuneOut before you try to point OBS to the file.

**Comment by Ula492** [comment]
Yes, I know this. But when i click the file on OBS, and try to find the file it will not work, I cant type it either.

**Comment by wonaldson** [comment]
You should be able to hit Command-Shift-G in the file chooser dialog to open the Go to Folder dialog. If you paste `~/Library/Application Support/TuneOut/` in the field that comes up it should bring you straight to the folder. The `Library` user folder is hidden by default, which is probably why you weren't able to find it. Let me know if this doesn't work for you.
