### ISSUE TITLE
Adding space between artist name and song name!?

### ISSUE THREAD

**Issue by AppleDeveloperBCN** [wonaldson/tuneout#19]
Hi, I want to know how I can split the artist name from the song name because in my OBS Text object, I have a scroll filter and when all the text moves, it starts again but without space. So, the last letter of the song's name is touching the first letter of the artist's name.

Thanks!

**Comment by purrloftruth** [comment]
This can be done in OBS with a filter. If I recall correctly it’s called “crop/pad” or something similar. You can add extra padding to the end of the line before the scroll itself. I’m no longer actively maintaining this software, so I wouldn’t be able to add a feature to add spaces to the end, and I haven’t been able to work on its replacement (which is a complete rewrite).
